# Generated by Django 3.1.2 on 2020-10-16 21:12

from django.db import migrations, models
import django.db.models.deletion
import landing_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel_number', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('H', 'Health Insurance Company Worker'), ('A', 'Admin')], default='P', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Y', 'Inwaiting'), ('M', 'Missed'), ('C', 'Completed'), ('A', 'Aborted')], default='Y', max_length=1)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True)),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='landing_page.user')),
                ('id_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.problem')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to='landing_page.user')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.user'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True)),
                ('id_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.problem')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=landing_page.models.user_directory_path)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.DateTimeField(blank=True)),
                ('id_health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.healthrecord')),
            ],
        ),
    ]
