# Generated by Django 3.1.2 on 2020-10-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='closed',
        ),
        migrations.AddField(
            model_name='user',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
