# Generated by Django 3.1.2 on 2020-11-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalact',
            old_name='name',
            new_name='description',
        ),
    ]
