# Generated by Django 3.1.2 on 2020-11-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_died',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telephone number'),
        ),
    ]
