# Generated by Django 3.1.2 on 2020-11-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_auto_20201126_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.problem'),
        ),
    ]
