# Generated by Django 3.1.2 on 2020-11-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_auto_20201130_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalact',
            name='id_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_medical_acts',
            field=models.ManyToManyField(blank=True, null=True, to='hospital_app.MedicalAct'),
        ),
    ]
