# Generated by Django 3.1.2 on 2020-11-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20201126_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='state',
        ),
    ]
