# Generated by Django 3.1.2 on 2020-11-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20201130_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalact',
            name='covered',
        ),
        migrations.AddField(
            model_name='medicalact',
            name='coverable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MedicalCompensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covered', models.BooleanField(default=False)),
                ('id_medical_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medicalact')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_medical_acts',
            field=models.ManyToManyField(blank=True, to='hospital_app.MedicalCompensation'),
        ),
    ]
