# Generated by Django 3.1.2 on 2020-11-30 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_auto_20201130_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.problem'),
        ),
    ]
