# Generated by Django 3.1.2 on 2020-11-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_remove_problem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='state',
            field=models.CharField(choices=[('M', 'In progress'), ('C', 'Completed'), ('A', 'Aborted')], default='M', max_length=1),
        ),
    ]
