# Generated by Django 3.1.2 on 2020-11-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_problem_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='id_ticket',
        ),
    ]
