# Generated by Django 3.1.2 on 2020-11-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_medicalcompensation_linked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_closed',
        ),
    ]
