# Generated by Django 3.1.2 on 2020-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_remove_file_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('W', 'Wanted'), ('Y', 'Inwaiting'), ('M', 'Missed'), ('C', 'Completed'), ('A', 'Aborted')], default='Y', max_length=1),
        ),
    ]
